# Generated by Django 5.1.7 on 2025-03-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('situation', models.CharField(choices=[('unable', 'I am unable to travel to the US, or it is not safe for me to travel.'), ('unwilling', 'I am refusing to travel in solidarity.')], max_length=64)),
                ('public', models.BooleanField(blank=True)),
                ('validated', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
