# Generated by Django 5.1.7 on 2025-03-20 10:35

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='token',
            field=models.CharField(default=main.models.make_token, max_length=255, unique=True),
        ),
    ]
